dist:
    module: github.com/appare45/my-otel-collector
    output_path: ./output
exporters:
    - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.116.0

processors:
    - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.122.1
    - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.122.0

receivers:
    - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.122.0
