receivers:
    hostmetrics:
        scrapers:
            cpu:
            disk:
            filesystem:
            load:
            memory:
            network:
            paging:

processors:
    batch:
        timeout: 1m

exporters:
    otlp/mackerel:
        endpoint: otlp.mackerelio.com:4317
        compression: gzip
        headers:
            Mackerel-Api-Key: ${env:MACKEREL_APIKEY}

service:
    pipelines:
        metrics:
            receivers: [hostmetrics]
            processors: [batch]
            exporters: [otlp/mackerel]
