name: Build Collector

on: [push]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - name: macos-14
                      GOBIN: /Users/runner/gobin
                    - name: ubuntu-24.04
                      GOBIN: /opt/gobin
        runs-on: ${{matrix.os.name}}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22
                  cache-dependency-path: builder-config.yaml
            - name: Cache Builder
              uses: actions/cache@v4
              with:
                  path: ${{matrix.os.GOBIN}}
                  key: ${{runner.os}}-${{runner.arch}}-gobin
            - name: Install Builder
              run: go install go.opentelemetry.io/collector/cmd/builder@latest
            - name: Build Collector
              run: ${{matrix.os.GOBIN}}/builder --config=builder-config.yaml
