name: Build Collector

on: [push]

env:
    GOBIN: /Users/runner/gobin

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-14, ubuntu-24.04]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v4
            - name: Set GOBIN
              run: echo "GOBIN=$RUNNER_TEMP/gobin" | tee $GITHUB_ENV
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22
                  cache-dependency-path: builder-config.yaml
            - name: Cache Builder
              uses: actions/cache@v4
              with:
                  path: ${{env.GOBIN}}
                  key: ${{runner.os}}-${{runner.arch}}-gobin
            - name: Install Builder
              run: go install go.opentelemetry.io/collector/cmd/builder@latest
            - name: Build Collector
              run: $GOBIN/builder --config=builder-config.yaml
