name: Build Collector

on:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-14, ubuntu-24.04]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v4
            - name: Set GOBIN
              run: echo "GOBIN=$RUNNER_TEMP/gobin" | tee $GITHUB_ENV
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22
                  cache-dependency-path: builder-config.yaml
            - name: Cache Builder
              uses: actions/cache@v4
              with:
                  path: ${{env.GOBIN}}
                  key: ${{runner.os}}-${{runner.arch}}-gobin
            - name: Install Builder
              run: go install go.opentelemetry.io/collector/cmd/builder@latest
            - name: Build Collector
              run: $GOBIN/builder --config=builder-config.yaml && mv ./output/my-otel-collector ./output/my-otel-collector-${{matrix.os}}
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: temp-${{matrix.os}}-${{github.run_id}}
                  path: ./output/my-otel-collector-${{matrix.os}}
                  retention-days: 1
    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v4
              with:
                  merge-multiple: true
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  fail_on_unmatched_files: true
                  tag_name: ${{ steps.tag_version.outputs.new_tag }}
                  files: |
                      my-otel-collector-*
